image:
    repository: singhjeet18/devops-project
    tag: "9d0d603"
    pullPolicy: IfNotPresent
service:
    type: ClusterIP
    port: 8080
ingress:
    enabled: false
serviceAccount:
    enabled: false
autoscaling:
    enabled: false
    
