---

name: devops-project

on:
  push:
    branches:
      - main
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set Short SHA
        run: |
          echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t singhjeet18/devops-project:${{ env.SHORT_SHA }} .

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
      - name: Push to DockerHub
        run: |
          docker push singhjeet18/devops-project:${{ env.SHORT_SHA }}
      - name: Conguar Git Author
        run: |
          git config --local user.name "singhjeet18"
          git config --local user.email "singhjitesh9584@gmail.com"
      - name: Update Helm Chart with new image
        run: |
          sed -i "s/tag:.*/tag: \"$SHORT_SHA\"/" ./devops-project-time-printer/values.yaml
          git add ./devops-project-time-printer/values.yaml
          git commit -m "Update image tag to $SHORT_SHA"
          git push
        env:
          SHORT_SHA: ${{ env.SHORT_SHA }}
